{
 "title": "GRR - dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Infos service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nombre d'utilisateurs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grr_utilisateurs", "legendFormat": "Utilisateurs" }
   ]
  },
  {
   "title": "Nombre de type de réservations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grr_type_area", "legendFormat": "Utilisateurs" }
   ]
  },
  {
   "title": "Nombre de réservations par jour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(increase(grr_entry[24h]))", "legendFormat": "Réservations" }
   ]
  },
  {
   "title": "Nombre de réservations total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    { "expr": "grr_entry", "legendFormat": "Réservations" }
   ]
  },
  { "title": "Infos systèmes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Etat du service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unit_application_healthz_processes_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evolution du nombre de connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "increase(unit_connections_accepted_total[5m])",
     "legendFormat": "connexions"
    }
   ]
  }
 ]
}